version: "3"
services:
  jupyter:
    #build: .
    image:  continuumio/anaconda3
    volumes:
      - ~/tmp:/tmp/working
    working_dir: /tmp/working
    ports:
      - 1234:8888
    command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''