apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv001
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce
  #storageClassName: hostpath
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  hostPath:
    path: /C/k/share/ubuntu
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       #- key: docker.io/hostname
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv002
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  local:
    path: /C/k/share/ubuntu2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop

          
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv003
  labels:
    type: grafana
spec:
  capacity:
    storage: 5Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  local:
    path: /host_mnt/C/k/share/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop