apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ubuntu-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  
  # volumeMode: Block
  storageClassName: local-storage
  selector:
    matchLabels:
      type: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # volumeMode: Block
  storageClassName: hostpath
  selector:
    matchLabels:
      vol: mysql

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-ubuntu2-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # volumeMode: Block
  storageClassName: hostpath
  selector:
    matchLabels:
      type: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-grafana-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # volumeMode: Block
  storageClassName: hostpath
  selector:
    matchLabels:
      type: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaniko-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
  # volumeMode: Block
  storageClassName: hostpath
  selector:
    matchLabels:
      type: kaniko