apiVersion: v1
kind: Pod
metadata:
  name: ubuntu18
  labels:
    app: ubuntu18
spec:
  containers:
    - image: ubuntu:18.04
      name: ubuntu18
      command:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: /mnt
          name: mount-volume
        - mountPath: /mnt2
          name: mount-volume2
  restartPolicy: OnFailure
  volumes:
    - name: mount-volume
      # hostPath:
      #  path: /c/k/share/ubuntu
      #  type: DirectoryOrCreate    
      persistentVolumeClaim:
         claimName: local-ubuntu-claim
    - name: mount-volume2
      # hostPath:
      #  path: /c/k/share/ubuntu
      #  type: DirectoryOrCreate    
      persistentVolumeClaim:
          claimName: local-ubuntu2-claim