version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ~/tmp:/tmp/working
    working_dir: /tmp/working
    ports:
      - '1234:8888'
      - '1022:22'
    #runtime: nvidia
    #command: /bin/bash -c "/usr/sbin/sshd -D && jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''"
    #command: jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.token=''
    command: /bin/bash -c "/usr/sbin/sshd -D"
