apiVersion: v1
kind: Service
metadata:
  name: mysql-loadbalancer
spec:
    selector:
      app: mysql
    ports:
    - port: 3306
      targetPort: 3306
    type: LoadBalancer
    loadBalancerIP: "127.0.0.1"