apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # volumeMode: Block
  storageClassName: hostpath
  selector:
    matchLabels:
      vol: mysql

