
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic0-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce
  #storageClassName: hostpath
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  hostPath:
    path: /C/k/share/elastic0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic1-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteOnce
  #storageClassName: hostpath
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  hostPath:
    path: /C/k/share/elastic1
