apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
  labels:
    k8s-app: elasticsearch-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Elasticsearch"
spec:
  selector:
    k8s-app: elasticsearch-logging
  clusterIP: None
  ports:
  - port: 9200
    name: db
  - port: 9300
    name: transport
